package com.example.pdfnotemate.utils

object BundleArguments {

    const val ARGS_PAGE_TYPE = "ARGS_PAGE_TYPE"
    const val ARGS_PDF_DETAILS = "ARGS_PDF_DETAILS"
    const val ARGS_COMMENT = "ARGS_COMMENT"
    const val ARGS_COMMENTS = "ARGS_COMMENTS"
    const val ARGS_HIGHLIGHT = "ARGS_HIGHLIGHT"
    const val ARGS_HIGHLIGHTS = "ARGS_HIGHLIGHTS"
    const val ARGS_BOOKMARK = "ARGS_BOOKMARK"
    const val ARGS_BOOKMARKS = "ARGS_BOOKMARKS"
    const val ARGS_DELETED_COMMENT_IDS = "ARGS_DELETED_COMMENT_IDS"
    const val ARGS_DELETED_HIGHLIGHT_IDS = "ARGS_DELETED_HIGHLIGHT_IDS"
    const val ARGS_DELETED_BOOKMARK_IDS = "ARGS_DELETED_BOOKMARK_IDS"
}